1.6
yakovleval/spbu-tasks-1-term pull request #6
Opened 2022-09-08 20:42 UTC by yakovleval

2022-09-11 14:27 UTC, Lozov-Petr requested changes

2022-09-11 14:27 UTC, Lozov-Petr commented on hw1/1.6/main.c
> +    strcat(resultString, "$");
а если в строках содержится символ '$'?

2022-09-24 04:53 UTC, Lozov-Petr requested changes

2022-09-24 04:53 UTC, Lozov-Petr commented on hw1/1.6/main.c
> +    strcat(resultString, "$");
Этот символ по-прежнему используется...

2022-09-24 17:05 UTC, yakovleval commented on hw1/1.6/main.c
> +    strcat(resultString, "$");
а как без него сконкатенировать строки через символ? я же его потом заменяю на терминирующий ноль, в исходной строке он вроде всегда означает конец строки.

> Этот символ по-прежнему используется...

2022-09-26 18:36 UTC, merged

2022-09-29 03:08 UTC, Lozov-Petr commented on hw1/1.6/main.c
> +    strcat(resultString, "$");
Например, перенос строки не может содержаться во входных строках из scanf.